### ISSUE TITLE
Thank you for the support!

### ISSUE THREAD

**Issue by PySimpleGUI** [econ-RUBICS/RUBICS#1]
Thank you Sam for the generous and heartfelt show of support  ![image](https://github.com/econ-RUBICS/RUBICS/assets/46163555/c5698078-81ca-4f1f-a8ce-ecbc7d0ee0a5)

![image](https://github.com/econ-RUBICS/RUBICS/assets/46163555/fd1e5d3e-bf9e-4698-ad9a-8ec18ebe7adc)

You made my day and I passed your message around to the rest of the team.  

Drop a screenshot in your readme as you did on your website.  I'm sure visitors will be interested in seeing what you made.  You can even use the image below by pasting the line of markdown github created when I pasted the image:
`![image](https://github.com/econ-RUBICS/RUBICS/assets/46163555/f1ae3521-efd6-4818-b57a-d6bc638a3699)`

![image](https://github.com/econ-RUBICS/RUBICS/assets/46163555/f1ae3521-efd6-4818-b57a-d6bc638a3699)

I really appreciated your message.  Gratitude has fueled the project.  It's awesome knowing we're having an impact.  That meaning thing.... it's good stuff.

-mike

**Comment by econ-RUBICS** [comment]
Hi Mike, 

Thanks for the tip! If you've had a look at this project then I'm sure you can tell that I'm learning a lot, and so much of this is new to me :)

I'll be sure to take this one on board. 

Sam

**Comment by PySimpleGUI** [comment]
You've **done** a lot, not just learning a lot.  Very impressive work.
