### ISSUE TITLE
Error message closes the app

### ISSUE THREAD

**Issue by Jatraj1** [econ-RUBICS/RUBICS#3]
https://github.com/econ-RUBICS/RUBICS/blame/141fb6ee23d29554f9af956ebf12c15ac33f1584/RUBICS.py#L3173C35-L3173C38

![image](https://github.com/econ-RUBICS/RUBICS/assets/127613466/1f4d3673-8569-4e37-96ba-e5b69288bfbf)

You should try to implement something like this:
```
if event == '-RES_RUN-':
    try:
        print("results")
        #all your code
    except ValueError:
        print("An exception occurred")
        #create a pop-up to show the user without closing the app
```

**Comment by econ-RUBICS** [comment]
Hi Jatraj1,

That is a good idea, I will implement that in the next update :)

Thankyou!
